# Generated by Django 5.0 on 2024-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_realisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('image_google', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_avis', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
